Add serialVersionUID to a class implements to Serializable
apache/incubator-uniffle pull request #1960
Opened 2024-07-25 14:09 UTC by maobaolong

### What changes were proposed in this pull request?

(Please outline the changes and how this PR fixes the issue.)

### Why are the changes needed?

(Please clarify why the changes are needed. For instance,
  1. If you propose a new API, clarify the use case for a new API.
  2. If you fix a bug, describe the bug.)

Fix: # (issue)

### Does this PR introduce _any_ user-facing change?

(Please list the user-facing changes introduced by your change, including
  1. Change in user-facing APIs.
  2. Addition or removal of property keys.)

No.

### How was this patch tested?

(Please test your changes, and provide instructions on how to test it:
  1. If you add a feature or fix a bug, add a test to cover your changes. 
  2. If you fix a flaky test, repeat it for many times to prove it works.)

2024-07-25 14:27 UTC, rickyma requested changes

2024-07-25 14:27 UTC, rickyma commented on client-spark/common/src/main/java/org/apache/spark/shuffle/RssShuffleHandle.java
> +  private static final long serialVersionUID = -5519528926859572710L;
I think we need to define this to `0L` like what Spark does currently. 

> Zero means "compute the version id at runtime by applying the standard algorithm" based on the actual class that you are serializing / deserializing. That means that whenever your code's effective serialization signature changes, the serialization / deserialization code will use a different version id

Refer to https://stackoverflow.com/a/21851309/9217742.

2024-07-26 00:57 UTC, maobaolong commented
@rickyma Thanks for your review and suggestion, addressed it by new commit,  PTAL.

2024-07-26 02:56 UTC, rickyma commented on client-spark/common/src/main/java/org/apache/spark/shuffle/handle/SimpleShuffleHandleInfo.java
> +
Remove this newline

2024-07-26 06:45 UTC, maobaolong commented on client-spark/common/src/main/java/org/apache/spark/shuffle/handle/SimpleShuffleHandleInfo.java
> +
Done

2024-07-26 06:46 UTC, maobaolong commented
@rickyma Newline removed, PTAL

2024-07-26 06:54 UTC, rickyma commented
> Add serialVersionUID to each class of implements to Serializable, to avoid

Please complete your description.

2024-07-26 07:01 UTC, maobaolong commented
> > Add serialVersionUID to each class of implements to Serializable, to avoid
> 
> Please complete your description.

Done

2024-07-26 07:02 UTC, maobaolong commented
> > Fix: #1961
> > No.
> 
> You deleted the title.

Removed by accident, added it back, PTAL

2024-07-26 07:10 UTC, rickyma approved these changes
LGTM

2024-07-26 07:10 UTC, merged

2024-07-26 07:11 UTC, maobaolong commented
@rickyma Thanks for your review!